/******************************************************************************
 * gpkg.js
 *
 * Reads a GeoPackage generated by GeoPandas.
 *
 ******************************************************************************/
/******************************************************************************
 * gpkg.js
 ******************************************************************************/

 export async function loadGeoPackage(file) {

    const buffer = await file.arrayBuffer();

    const bytes = new Uint8Array(buffer);

    const gpkg =
        await GeoPackage.GeoPackageAPI.open(bytes);

    console.log("Opened:", file.name);
    console.log("Size:", file.size);

    const tables =
        gpkg.connection.adapter.db.exec(
            "SELECT name FROM sqlite_master WHERE type='table'"
        );

    console.log("SQLite tables:", tables);

    console.log("GeoPackage opened");


    const table = "media_inventory";


    const photos = [];


    const iterator =
        gpkg.iterateGeoJSONFeatures(table);


    for (const feature of iterator) {
        try{
            console.log("Feature:", feature);


            if (!feature.geometry)
                continue;


            const p = feature.properties;

            if (p.media_type !== "image")
                continue;


            photos.push({

                filename: p.filename,

                filepath: p.filepath,

                media_type: p.media_type,

                caption: p.caption,

                geometry: feature.geometry,

                longitude:
                    feature.geometry.coordinates[0],

                latitude:
                    feature.geometry.coordinates[1]

            });
        }catch(e){

            console.warn(
                "Skipping bad geometry",
                e
            );

        }
    }

    console.log(
        "Loaded photos:",
        photos.length
    );


    return photos;
}


/******************************************************************************
 * Parse JSON safely
 ******************************************************************************/

function parseJSON(value) {

    if (!value)
        return [];

    try {

        return JSON.parse(value);

    }

    catch {

        return [];

    }

}
